### ISSUE TITLE
Sonic doesn't work as expected.

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/Sonic-Screwdriver#10]
(Links to #150)

The Sonic screwdriver could still alter the destination after the TARDIS vent to vortex.
This is no longer possible.

Reproducing:
1. Spawn a TARDIS.
2. Link it.
3. Enable long flight if Legacy.
4. Mark Destination at point A with the sonic.
5. Dematerialize it with R
6. Mark Destination at point B with the sonic.
7. Rematerialize it with R
8. Watch the TARDIS go to point A.

Is there a way to Imitate the legacy by making it go to point B?

**Comment by MattJeanes** [comment]
Fixed in https://github.com/MattJeanes/TARDIS/issues/230
