### ISSUE TITLE
Third Party Integration

### ISSUE THREAD

**Issue by ThePademelon** [MattJeanes/Sonic-Screwdriver#11]
Hi, I'm working on a mod and I'd like to make it compatible with the screwdriver. I've poked through your code but I can't seem to figure out how to get the screwdriver to invoke a hook on my entity without doing something hacky like changing my base class. Am I missing something or is there no way to do it at the moment?

**Comment by MattJeanes** [comment]
Hello, you can indeed add stuff yourself.

If you put your lua module file thing into `lua/weapons/swep_sonicsd/modules` like mine, even in your own addon then the sonic will load it up when it starts.

**Comment by ThePademelon** [comment]
Oh nice, that's quite intuitive. I'll give it a shot, thanks!

**Comment by ThePademelon** [comment]
Thanks for the help!
https://youtu.be/Ni-zv1FpNCU

**Comment by MattJeanes** [comment]
Looks awesome, glad to see you got it working alright.
