### ISSUE TITLE
Linking tardis

### ISSUE THREAD

**Issue by reede2** [MattJeanes/Sonic-Screwdriver#14]
Users now complain saying its saying that they dont own the tardis even know they do  when they try to use the sonic on the outside and inside

**Comment by MattJeanes** [comment]
What? You got a screenshot or something it the sonic doesn't tell you you don't own it

**Comment by reede2** [comment]
no beacuse i can do it as my rank but they cant as user

**Comment by reede2** [comment]
and the other staff ranks cant only me as founder can i dont know how to change it

**Comment by reede2** [comment]
also geting this error with tardis 
[ERROR] lua/entities/gmod_tardis/modules/sh_doors.lua:176: attempt to index field 'metadata' (a nil value)
  1. v - lua/entities/gmod_tardis/modules/sh_doors.lua:176
   2. CallHook - lua/entities/gmod_tardis/shared.lua:37
    3. unknown - lua/entities/gmod_tardis/modules/sh_doors.lua:172
     4. func - lua/entities/gmod_tardis/modules/libraries/sh_message.lua:34
      5. unknown - lua/includes/extensions/net.lua:32

**Comment by MattJeanes** [comment]
It looks like however you're spawning the tardis it isn't associating the owner with it properly, how are you spawning them?

**Comment by reede2** [comment]
fro mf4

**Comment by MattJeanes** [comment]
No I mean the code that spawns it

**Comment by reede2** [comment]
DarkRP.createEntity("The TARDIS", {
	ent = "gmod_tardis",
	model = "models/the_sniper_9/doctorwho/tardis/tardis.mdl",
	price = 100,
	max = 1,
	cmd = "TARDIs",
	category = "TimeLords",
	customCheck = function(ply) return CLIENT or
	table.HasValue({TEAM_DOCTOR, TEAM_MASTER, TEAM_TIMELORD, TEAM_RANI}, ply:Team())
	end,
	CustomCheckFailMsg = "You can not buy this",
	spawn = function(ply, tr, tblEnt)
		tr.Hit = true
		return scripted_ents.Get(tblEnt.ent):SpawnFunction(ply, tr, tblEnt.ent)
	end,
})

**Comment by MattJeanes** [comment]
```lua
DarkRP.createEntity("The TARDIS", {
	ent = "gmod_tardis",
	model = "models/the_sniper_9/doctorwho/tardis/tardis.mdl",
	price = 100,
	max = 1,
	cmd = "TARDIS",
	category = "TimeLords",
	customCheck = function(ply) return CLIENT or
	table.HasValue({TEAM_DOCTOR, TEAM_MASTER, TEAM_TIMELORD, TEAM_RANI}, ply:Team())
	end,
	CustomCheckFailMsg = "You can not buy this",
	spawn = function(ply, tr, tblEnt)
		tr.Hit = true
		local ent = scripted_ents.Get(tblEnt.ent):SpawnFunction(ply, tr, tblEnt.ent)
		print("TARDIS Owner: ", ent.owner)
		return ent
	end,
})
```

Can you try the code above and tell me what it says in the server console when you spawn it?

**Comment by reede2** [comment]
TARDIS Owner: 	nil

**Comment by MattJeanes** [comment]
Interesting okay, can you try the new code and see if it works now?

**Comment by reede2** [comment]
still TARDIS Owner: 	nil

**Comment by MattJeanes** [comment]
It shouldn't be saying anything at all anymore, see if your issue with linking is fixed after restarting the server

**Comment by reede2** [comment]
they say they can lock  but not link and i get this in console 
[ERROR] lua/entities/gmod_tardis/modules/sh_lock.lua:67: attempt to index field 'metadata' (a nil value)

  1. unknown - lua/entities/gmod_tardis/modules/sh_lock.lua:67

   2. func - lua/entities/gmod_tardis/modules/libraries/sh_message.lua:34

    3. unknown - lua/includes/extensions/net.lua:32

**Comment by MattJeanes** [comment]
Hmm okay, can you try the above one and see if anyone gets any errors and let me know what appears in the server console?

**Comment by reede2** [comment]
creator: 	Player [1][[MV] Reede]

owner: 	nil

**Comment by MattJeanes** [comment]
It should say something about metadata as well?

**Comment by reede2** [comment]
creator: 	Player [1][[MV] Reede]

owner: 	nil

metadata: 	table: 0x2146bd80

**Comment by MattJeanes** [comment]
Ok can you try the new one again and see if the sonic works when linking it and stuff

**Comment by reede2** [comment]
i can link it but everyone else cant ithink can you come on the server and i can show you

**Comment by reede2** [comment]
?

**Comment by MattJeanes** [comment]
I can't join right now but I might be able to later, what are your server details?

**Comment by reede2** [comment]
185.38.148.134:27075

**Comment by KyberNetworks** [comment]
just checking back to this has linking tardis been removed ?

**Comment by MattJeanes** [comment]
Nope, should work same as always, but you must have prop protection ability over the TARDIS being linked
