### ISSUE TITLE
Different hold types for different actions?

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/Sonic-Screwdriver#8]
What if the player holds the Sonic in the: 

-Revolver fashion upon tracking down something, 
-Crowbar like for Torch Mode,
-fist Style for door interaction,
and pistol Style for others actions?

I have noticed the Sonic actually switched randomly thru hold types. I don't know if this is on purpose?

**Comment by MattJeanes** [comment]
I've investigated hold types and found no way to dynamically change this unfortunately, so I will close this
